//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApplication")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderInfo", Namespace="http://schemas.datacontract.org/2004/07/BO")]
    public partial class HeaderInfo : object
    {
        
        private string CallStatusField;
        
        private string TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallStatus
        {
            get
            {
                return this.CallStatusField;
            }
            set
            {
                this.CallStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentBO", Namespace="http://schemas.datacontract.org/2004/07/BO")]
    public partial class StudentBO : object
    {
        
        private int IdField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private int RollNoField;
        
        private int MarksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RollNo
        {
            get
            {
                return this.RollNoField;
            }
            set
            {
                this.RollNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Marks
        {
            get
            {
                return this.MarksField;
            }
            set
            {
                this.MarksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudentervice")]
    public interface IStudentervice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/GetData", ReplyAction="http://tempuri.org/IStudentervice/GetDataResponse")]
        StudentService.GetDataResponse GetData(StudentService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/GetData", ReplyAction="http://tempuri.org/IStudentervice/GetDataResponse")]
        System.Threading.Tasks.Task<StudentService.GetDataResponse> GetDataAsync(StudentService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentervice/GetDataUsingDataContractResponse")]
        StudentService.GetDataUsingDataContractResponse GetDataUsingDataContract(StudentService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentervice/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<StudentService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(StudentService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/Welcome", ReplyAction="http://tempuri.org/IStudentervice/WelcomeResponse")]
        StudentService.WelcomeResponse Welcome(StudentService.WelcomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/Welcome", ReplyAction="http://tempuri.org/IStudentervice/WelcomeResponse")]
        System.Threading.Tasks.Task<StudentService.WelcomeResponse> WelcomeAsync(StudentService.WelcomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/CreateStudent", ReplyAction="http://tempuri.org/IStudentervice/CreateStudentResponse")]
        StudentService.StudentInfoResponse CreateStudent(StudentService.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/CreateStudent", ReplyAction="http://tempuri.org/IStudentervice/CreateStudentResponse")]
        System.Threading.Tasks.Task<StudentService.StudentInfoResponse> CreateStudentAsync(StudentService.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/UpdateStudent", ReplyAction="http://tempuri.org/IStudentervice/UpdateStudentResponse")]
        StudentService.StudentInfoResponse UpdateStudent(StudentService.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/UpdateStudent", ReplyAction="http://tempuri.org/IStudentervice/UpdateStudentResponse")]
        System.Threading.Tasks.Task<StudentService.StudentInfoResponse> UpdateStudentAsync(StudentService.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/DeleteStudent", ReplyAction="http://tempuri.org/IStudentervice/DeleteStudentResponse")]
        StudentService.StudentInfoResponse DeleteStudent(StudentService.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentervice/DeleteStudent", ReplyAction="http://tempuri.org/IStudentervice/DeleteStudentResponse")]
        System.Threading.Tasks.Task<StudentService.StudentInfoResponse> DeleteStudentAsync(StudentService.StudentInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(StudentService.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(StudentService.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Welcome", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WelcomeRequest
    {
        
        public WelcomeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WelcomeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WelcomeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string WelcomeResult;
        
        public WelcomeResponse()
        {
        }
        
        public WelcomeResponse(string WelcomeResult)
        {
            this.WelcomeResult = WelcomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentInfoRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StudentService.HeaderInfo Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.StudentBO Body;
        
        public StudentInfoRequest()
        {
        }
        
        public StudentInfoRequest(StudentService.HeaderInfo Header, StudentService.StudentBO Body)
        {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentInfoResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StudentService.HeaderInfo Header;
        
        public StudentInfoResponse()
        {
        }
        
        public StudentInfoResponse(StudentService.HeaderInfo Header)
        {
            this.Header = Header;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IStudenterviceChannel : StudentService.IStudentervice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class StudenterviceClient : System.ServiceModel.ClientBase<StudentService.IStudentervice>, StudentService.IStudentervice
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StudenterviceClient() : 
                base(StudenterviceClient.GetDefaultBinding(), StudenterviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStudentervice.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudenterviceClient(EndpointConfiguration endpointConfiguration) : 
                base(StudenterviceClient.GetBindingForEndpoint(endpointConfiguration), StudenterviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudenterviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StudenterviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudenterviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StudenterviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudenterviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public StudentService.GetDataResponse GetData(StudentService.GetDataRequest request)
        {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetDataResponse> GetDataAsync(StudentService.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public StudentService.GetDataUsingDataContractResponse GetDataUsingDataContract(StudentService.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(StudentService.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public StudentService.WelcomeResponse Welcome(StudentService.WelcomeRequest request)
        {
            return base.Channel.Welcome(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.WelcomeResponse> WelcomeAsync(StudentService.WelcomeRequest request)
        {
            return base.Channel.WelcomeAsync(request);
        }
        
        public StudentService.StudentInfoResponse CreateStudent(StudentService.StudentInfoRequest request)
        {
            return base.Channel.CreateStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.StudentInfoResponse> CreateStudentAsync(StudentService.StudentInfoRequest request)
        {
            return base.Channel.CreateStudentAsync(request);
        }
        
        public StudentService.StudentInfoResponse UpdateStudent(StudentService.StudentInfoRequest request)
        {
            return base.Channel.UpdateStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.StudentInfoResponse> UpdateStudentAsync(StudentService.StudentInfoRequest request)
        {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        public StudentService.StudentInfoResponse DeleteStudent(StudentService.StudentInfoRequest request)
        {
            return base.Channel.DeleteStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.StudentInfoResponse> DeleteStudentAsync(StudentService.StudentInfoRequest request)
        {
            return base.Channel.DeleteStudentAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentervice))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentervice))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54072/StudentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StudenterviceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStudentervice);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StudenterviceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStudentervice);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStudentervice,
        }
    }
}
